project:
  type: website
  output-dir: docs

website:
  title: "Felix Schulz"
  navbar:
    search: false
  page-footer: |
    © 2024 Felix Schulz. All rights reserved.  
    This website is built using Quarto.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



